# Please do not touch - A.V

# Data Source Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_ADMIN}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Encryption Secret Key
encryption.secret-key=${ENCRYPTION_SECRET_KEY}

# JWT Secret Key
jwt.secret-key=${JWT_SECRET_KEY}

# Mailing Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA Configuration (Keep hibernate value none unless explicitly updating database schema)
spring.jpa.hibernate.ddl-auto=none 
spring.jpa.show-sql=true

# Server Configuration
server.port=8080

# Disables Spring Security to keep endpoints public on local network during development
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration