# Data Source Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_ADMIN}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Server Configuration
server.port=8080

# Disables Spring Security to keep endpoints public on local network during development
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration